### PR TITLE
Try a new modern navigation menu and admin bar

### PR DESCRIPTION
**Pull request by youknowriad**
This is largely incomplete, still buggy a little bit and missing a lot of styles but it gives you an idea on how we can achieve this and put us on track if this is something we want to tackle.

### CODE REVIEW

**Comment by melchoyce** [comment]
Hey @youknowriad, could you add some screenshots?

**Comment by youknowriad** [comment]
Sure 

Capture d’écran 2019-11-25 à 5 03 29 PM

The idea of this PR is to help you all (designers) use this as a starting point and move it forward to a mergeable state. I think there's somethings that can only be done properly in Core itself (and not in a plugin) but most of the changes can be worked on here.

**Comment by karmatosed** [comment]
This is super interesting @youknowriad and sorry took me so long to get around to feedback on this.

My first thoughts are it would be great to have a setting so people can choose it or not. Most experiments are done like that and super helpful to iterate on as a result.

image

Right off I think having the wp-admin bar dark and not blue can help ground it back in the work we have already in wp-admin, over feeling so dramatically different.

image

I quite like it without any icons but that's something to explore:

image

Once it's a setting and maybe the blue border is back to dark, let's get this in to try - thanks!

**Comment by youknowriad** [comment]
I don't have time to push thiis further.

**Pull request closed without merging**
