### PR TITLE
Try out a new header style

### PR DESCRIPTION
**Pull request by kjellr**
This experiment adds some (messy) styles to approximate a new header design in WP-Admin. For now, this only gets applied to the "Add Themes" page.

The general aesthetic is a bit more in line with Gutenberg and uses some Material Design patterns as well. Thanks @melchoyce for the initial mockups this is based on. 

Screen Shot 2019-04-30 at 9 26 26 AM

### CODE REVIEW

**Comment by alexislloyd** [comment]
I like this a lot, nice work! The white space and typography for the page title and the tabbed navigation design create a much stronger and clearer hierarchy. Can you talk a little about how you got here and other options you considered?

**Comment by melchoyce** [comment]
Hey @alexislloyd! Wanted to give some background on this experiment.

For a couple years, I've been thinking about unifying the disparate list pages: themes, plugins, posts, media, and comments. They all have similar header actions (bulk edit, filtering, swapping between list or grid view, etc.) but different ways of presenting those options. 

Here's an earlier exploration around unifying the headers:

image

A week or two ago, I was inspired to take another look at this, using some design systems as a base. I popped open the Material documentation and tried to apply its design choices to the page headers. That's how I ended up with this:

image

Kjell wanted to prototype it to get a feel for how it'd work live, and made this PR. It's one of hopefully many experiments, and by no means final. Just want to see how it'd work in action :)

**Comment by alexislloyd** [comment]
Thanks @melchoyce, that's super helpful! I like the direction this is going.

**Comment by draganescu** [comment]
My personal favourite thing is that little beauty of a grid option to list themes. I like to try themes and when I do I get a huge amount of screenshots which is so hard to browse that I never delete them :)))

**Comment by kjellr** [comment]
Merging this in so that others can try it out. 👍

**Comment by felipeloureirosantos** [comment]
That is really great.

I was looking into the <a href="https://github.com/WordPress/design-experiments/pull/5">settings page</a>, and the save button might be something that really needs be improved as the user needs scroll down and it is really bad user experience. What about creating a header to settings pages and put save button on it?

**Comment by kjellr** [comment]
Quick update here: In `ae777e9` I made some adjustments to expand this out to all settings pages. Still a little rough but it gives a better idea of how this would work. 

> I was looking into the settings page, and the save button might be something that really needs be improved as the user needs scroll down and it is really bad user experience. What about creating a header to settings pages and put save button on it?

That's a good thought, @felipeloureirosantos. If we allow ourselves a bit more whitespace like what's present in this experiment, I think elements like those buttons are a great thing to reassess too.

**Comment by felipeloureirosantos** [comment]
Really great.

I believe that there is a great pattern that we could get from Gutenberg.

We can see that it uses the right side on the header as a "add new items" idea. When we go to the left side the purpose is updating or publishing it.

post

Here we can see the default theme page on this experiment is already following this idea.

themes

Here is what I was wondering about. Something like that.

settings-general

Here we can see it using the right and left sides.

users

**Comment by Kleindberg** [comment]
I love new header's conseption! I hope it will be default in new versions of WordPress.

**Pull request merged**
